package com.model;

/**
 * TGoods generated by MyEclipse Persistence Tools
 */

public class TGoods implements java.io.Serializable
{

	// Fields

	private Integer goodsId;

	private String goodsName;

	private String goodsMiaoshu;

	private String goodsPic;

	private Integer goodsJiage;

	private Integer goodsCatelogId;

	private Integer goodsCanguanId;

	private String goodsDel;

	// Constructors

	/** default constructor */
	public TGoods()
	{
	}

	/** full constructor */
	public TGoods(String goodsName, String goodsMiaoshu, String goodsPic,
			Integer goodsJiage, Integer goodsCatelogId, Integer goodsCanguanId,
			String goodsDel)
	{
		this.goodsName = goodsName;
		this.goodsMiaoshu = goodsMiaoshu;
		this.goodsPic = goodsPic;
		this.goodsJiage = goodsJiage;
		this.goodsCatelogId = goodsCatelogId;
		this.goodsCanguanId = goodsCanguanId;
		this.goodsDel = goodsDel;
	}

	// Property accessors

	public Integer getGoodsId()
	{
		return this.goodsId;
	}

	public void setGoodsId(Integer goodsId)
	{
		this.goodsId = goodsId;
	}

	public String getGoodsName()
	{
		return this.goodsName;
	}

	public void setGoodsName(String goodsName)
	{
		this.goodsName = goodsName;
	}

	public String getGoodsMiaoshu()
	{
		return this.goodsMiaoshu;
	}

	public void setGoodsMiaoshu(String goodsMiaoshu)
	{
		this.goodsMiaoshu = goodsMiaoshu;
	}

	public String getGoodsPic()
	{
		return this.goodsPic;
	}

	public void setGoodsPic(String goodsPic)
	{
		this.goodsPic = goodsPic;
	}

	public Integer getGoodsJiage()
	{
		return this.goodsJiage;
	}

	public void setGoodsJiage(Integer goodsJiage)
	{
		this.goodsJiage = goodsJiage;
	}

	public Integer getGoodsCatelogId()
	{
		return this.goodsCatelogId;
	}

	public void setGoodsCatelogId(Integer goodsCatelogId)
	{
		this.goodsCatelogId = goodsCatelogId;
	}

	public Integer getGoodsCanguanId()
	{
		return this.goodsCanguanId;
	}

	public void setGoodsCanguanId(Integer goodsCanguanId)
	{
		this.goodsCanguanId = goodsCanguanId;
	}

	public String getGoodsDel()
	{
		return this.goodsDel;
	}

	public void setGoodsDel(String goodsDel)
	{
		this.goodsDel = goodsDel;
	}

}